# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79018fa54b83dec2d4908d711c46e795dad3089e3084bde25c50b0a48017a73007db245c29c642ecab8d384e3bb05e4998488436e6cf0dae55eed2bd5303b13b

test:
  secret_key_base: fb2d225ee897ffee3b2e2fb455593f99607a7c7a4bc4a89b575e5360abf555d42406cdbfab28807addb9edd78fd30ee0708f8b2f2cc33a151e77f5fcd1c139f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
